
Status: FAILED!
Reason: Unable to run main.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357421796_python-fundamentals-1e-90d64395-38b0-4952-862a-0c8397e7ddb5/9780357421796_python-fundamentals-1e-90d64395-38b0-4952-862a-0c8397e7ddb5/python/chapter5/ex06/main.py", line 4, in <module>
    print(x)
NameError: name 'x' is not defined

Timestamp: 2024-10-31 00:57:04.900573

Status: FAILED!
Reason: Unable to run main.py
Error: Traceback (most recent call last):
  File "/home/runner/work/9780357421796_python-fundamentals-1e-90d64395-38b0-4952-862a-0c8397e7ddb5/9780357421796_python-fundamentals-1e-90d64395-38b0-4952-862a-0c8397e7ddb5/python/chapter5/ex06/main.py", line 4, in <module>
    print(x)
NameError: name 'x' is not defined

Timestamp: 2024-10-31 00:57:04.900646

Status: FAILED!
Check: 1
Test: 
Reason: 
Error : AssertionError - Traceback (most recent call last):
  File "/home/runner/work/9780357421796_python-fundamentals-1e-90d64395-38b0-4952-862a-0c8397e7ddb5/9780357421796_python-fundamentals-1e-90d64395-38b0-4952-862a-0c8397e7ddb5/python/chapter5/ex06/main.py", line 4, in <module>
    print(x)
NameError: name 'x' is not defined

Timestamp: 2024-10-31 00:57:04.900693

Status: PASSED!
Check: 2
Test: Output is correct 2
Reason: else:
   print("You are all set with cars.")` was found in the program.None
Timestamp: 2024-10-31 00:57:04.901207

Status: PASSED!
Check: 3
Test: Declare a variable named `amt` that uses the `len` tuple method
Reason: amt = len(cars)` was found in the program.None
Timestamp: 2024-10-31 00:57:04.901434

Status: PASSED!
Check: 4
Test: Declare a variable named `fav` that uses the `count` tuple method
Reason: fav = cars.count("coupe")` was found in the program.None
Timestamp: 2024-10-31 00:57:04.901708
